services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-tests
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
